# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
