# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0003_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.CharField(default='Molex', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
